language: objective-c

before_install:
    - gem update
    - gem install cocoapods

script:
    - cd Demo
    - pod install
    - xctool clean build test -workspace Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator6.1
  