language: objective-c

before_install:
    - brew update
    - brew install xctool
    - gem update
    - gem install cocoapods

script:
    - cd Demo
    - pod install
    - xctool clean build run-tests -workspace Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator7.0
  
