language: objective-c
#xcode_workspace: AutoNSCodingDemo/AutoNSCodingDemo.xcworkspace
#xcode_project: MyNewProject.xcodeproj # path to your xcodeproj folder
#xcode_scheme: AutoNSCodingDemoTests

#before_install:
#    - pod install

script:
    - cd Demo
    - pod install
    - xctool test -workspace Demo/Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator7.0
  