language: objective-c

before_install:
    - gem update
    - gem install cocoapods

script:
    - cd Demo
    - pod install
    - xctool clean build -workspace Demo.xcworkspace -scheme DemoTests -sdk iphonesimulator7.1
  